#############################################################################
# Makefile for building: music
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  music.pro
# Template: app
# Command: /opt/Qt5.5.1/5.5/gcc/bin/qmake -spec linux-g++-32 CONFIG+=debug -o Makefile music.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++ -std=gnu++11 -O2
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m32 -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m32 -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/modex/ -I/opt/Qt5.5.1/5.5/gcc/include -I/opt/Qt5.5.1/5.5/gcc/include/QtWidgets -I/opt/Qt5.5.1/5.5/gcc/include/QtGui -I/opt/Qt5.5.1/5.5/gcc/include/QtCore -I. -I. -I/opt/Qt5.5.1/5.5/gcc/mkspecs/linux-g++-32
QMAKE         = /opt/Qt5.5.1/5.5/gcc/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = music1.0.0
DISTDIR = /home/alarm/Qt/NEW/music/.tmp/music1.0.0
LINK          = g++
LFLAGS        = -m32 -Wl,-rpath,/opt/Qt5.5.1/5.5/gcc -Wl,-rpath,/opt/Qt5.5.1/5.5/gcc/lib
LIBS          = $(SUBLIBS) -L/usr/lib -lfmodex -L/opt/Qt5.5.1/5.5/gcc/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp qrc_icons.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qrc_icons.o \
		moc_mainwindow.o
DIST          = /opt/Qt5.5.1/5.5/gcc/mkspecs/features/spec_pre.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/common/unix.conf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/common/linux.conf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/common/sanitize.conf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/common/gcc-base.conf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/common/g++-base.conf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/common/g++-unix.conf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/qconfig.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dcollision.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dcollision_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3drenderer.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/qt_functions.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/qt_config.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/linux-g++-32/qmake.conf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/spec_post.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/default_pre.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/resolve_config.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/default_post.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/warn_on.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/qt.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/resources.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/moc.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/uic.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/unix/thread.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/exceptions.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/yacc.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/lex.prf \
		music.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = music
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = music


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: music.pro /opt/Qt5.5.1/5.5/gcc/mkspecs/linux-g++-32/qmake.conf /opt/Qt5.5.1/5.5/gcc/mkspecs/features/spec_pre.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/common/unix.conf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/common/linux.conf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/common/sanitize.conf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/common/gcc-base.conf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/common/g++-base.conf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/common/g++-unix.conf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/qconfig.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dcollision.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dcollision_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3drenderer.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/qt_functions.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/qt_config.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/linux-g++-32/qmake.conf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/spec_post.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/default_pre.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/resolve_config.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/default_post.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/warn_on.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/qt.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/resources.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/moc.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/uic.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/unix/thread.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/exceptions.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/yacc.prf \
		/opt/Qt5.5.1/5.5/gcc/mkspecs/features/lex.prf \
		music.pro \
		icons.qrc \
		/opt/Qt5.5.1/5.5/gcc/lib/libQt5Widgets.prl \
		/opt/Qt5.5.1/5.5/gcc/lib/libQt5Gui.prl \
		/opt/Qt5.5.1/5.5/gcc/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++-32 CONFIG+=debug -o Makefile music.pro
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/spec_pre.prf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/common/unix.conf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/common/linux.conf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/common/sanitize.conf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/common/gcc-base.conf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/common/g++-base.conf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/common/g++-unix.conf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/qconfig.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dcollision.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dcollision_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dcore.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dinput.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dquick.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dquickrenderer.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3drenderer.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_3drenderer_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_declarative.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_enginio.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_location.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_location_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_script.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webengine.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webkit.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_webview_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/qt_functions.prf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/qt_config.prf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/linux-g++-32/qmake.conf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/spec_post.prf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/exclusive_builds.prf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/default_pre.prf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/resolve_config.prf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/default_post.prf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/warn_on.prf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/qt.prf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/resources.prf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/moc.prf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/unix/opengl.prf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/uic.prf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/unix/thread.prf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/testcase_targets.prf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/exceptions.prf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/yacc.prf:
/opt/Qt5.5.1/5.5/gcc/mkspecs/features/lex.prf:
music.pro:
icons.qrc:
/opt/Qt5.5.1/5.5/gcc/lib/libQt5Widgets.prl:
/opt/Qt5.5.1/5.5/gcc/lib/libQt5Gui.prl:
/opt/Qt5.5.1/5.5/gcc/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-32 CONFIG+=debug -o Makefile music.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents icons.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: icons.qrc \
		png/player_info.png \
		png/save.png \
		png/player_stop.png \
		png/player_rew.png \
		png/player_pause.png \
		png/player_play.png \
		png/player_repeat2.png \
		png/dsp_music.png \
		png/mute_off.png \
		png/player_repeat1.png \
		png/deletered.png \
		png/dsp.png \
		png/mute_on.png \
		png/folder_open2.png \
		png/media_audio.png \
		png/player_fwd.png
	/opt/Qt5.5.1/5.5/gcc/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QApplication \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qapplication.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qcoreapplication.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qglobal.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qconfig.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qfeatures.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qsystemdetection.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qprocessordetection.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qtypeinfo.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qtypetraits.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qsysinfo.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qlogging.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qflags.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qbasicatomic.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qgenericatomic.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_mips.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_x86.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_unix.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qglobalstatic.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qmutex.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qnumeric.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qstring.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qchar.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qbytearray.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qrefcount.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qnamespace.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qarraydata.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qstringbuilder.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qobject.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qobjectdefs.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qlist.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qalgorithms.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qiterator.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qbytearraylist.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qstringlist.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qregexp.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qstringmatcher.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qcoreevent.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qscopedpointer.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qmetatype.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qisenum.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qobject_impl.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qeventloop.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qwindowdefs.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qpoint.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qsize.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qcursor.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qwidget.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qmargins.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpaintdevice.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qrect.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpalette.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qcolor.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qrgb.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qbrush.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qpair.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qvector.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qmatrix.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpolygon.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qregion.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qdatastream.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qiodevice.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qline.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qtransform.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpainterpath.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qimage.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpixelformat.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpixmap.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qsharedpointer.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qshareddata.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qhash.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qfont.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qfontmetrics.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qfontinfo.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qkeysequence.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qevent.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qvariant.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qmap.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qdebug.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qtextstream.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qlocale.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qset.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qurl.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qurlquery.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qfile.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qfiledevice.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qvector2d.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qtouchdevice.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qguiapplication.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qinputmethod.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/QMouseEvent \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QString \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QStringList \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QDebug \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QIODevice \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QTextCodec \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qtextcodec.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QMutex \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QProgressBar \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qprogressbar.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qframe.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QFileDialog \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qfiledialog.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qdir.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qfileinfo.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qdialog.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QMainWindow \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qicon.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QDialog \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QDialogButtonBox \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qdialogbuttonbox.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QLineEdit \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qlineedit.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qtextcursor.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qtextformat.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpen.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qtextoption.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QMessageBox \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qmessagebox.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QTableWidget \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qtablewidget.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qtableview.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qabstractitemview.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qabstractscrollarea.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qabstractitemmodel.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qitemselectionmodel.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qabstractitemdelegate.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qstyleoption.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qabstractspinbox.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qvalidator.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qregularexpression.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qslider.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qabstractslider.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qstyle.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qtabbar.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qrubberband.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QTableWidgetItem \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QPushButton \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qpushbutton.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qabstractbutton.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QWidget \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QTableView \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QTextEdit \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qtextedit.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qtextdocument.h \
		mainwindow.h
	/opt/Qt5.5.1/5.5/gcc/bin/moc $(DEFINES) -I/opt/Qt5.5.1/5.5/gcc/mkspecs/linux-g++-32 -I/home/alarm/Qt/NEW/music -I/usr/include/modex -I/opt/Qt5.5.1/5.5/gcc/include -I/opt/Qt5.5.1/5.5/gcc/include/QtWidgets -I/opt/Qt5.5.1/5.5/gcc/include/QtGui -I/opt/Qt5.5.1/5.5/gcc/include/QtCore mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/opt/Qt5.5.1/5.5/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QApplication \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qapplication.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qcoreapplication.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qglobal.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qconfig.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qfeatures.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qsystemdetection.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qprocessordetection.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qtypeinfo.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qtypetraits.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qsysinfo.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qlogging.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qflags.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qbasicatomic.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qgenericatomic.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_mips.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_x86.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_unix.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qglobalstatic.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qmutex.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qnumeric.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qstring.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qchar.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qbytearray.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qrefcount.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qnamespace.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qarraydata.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qstringbuilder.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qobject.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qobjectdefs.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qlist.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qalgorithms.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qiterator.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qbytearraylist.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qstringlist.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qregexp.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qstringmatcher.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qcoreevent.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qscopedpointer.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qmetatype.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qisenum.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qobject_impl.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qeventloop.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qwindowdefs.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qpoint.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qsize.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qcursor.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qwidget.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qmargins.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpaintdevice.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qrect.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpalette.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qcolor.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qrgb.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qbrush.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qpair.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qvector.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qmatrix.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpolygon.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qregion.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qdatastream.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qiodevice.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qline.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qtransform.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpainterpath.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qimage.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpixelformat.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpixmap.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qsharedpointer.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qshareddata.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qhash.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qfont.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qfontmetrics.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qfontinfo.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qkeysequence.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qevent.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qvariant.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qmap.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qdebug.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qtextstream.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qlocale.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qset.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qurl.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qurlquery.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qfile.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qfiledevice.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qvector2d.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qtouchdevice.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qguiapplication.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qinputmethod.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/QMouseEvent \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QString \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QStringList \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QDebug \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QIODevice \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QTextCodec \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qtextcodec.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QMutex \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QProgressBar \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qprogressbar.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qframe.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QFileDialog \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qfiledialog.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qdir.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qfileinfo.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qdialog.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QMainWindow \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qicon.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QDialog \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QDialogButtonBox \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qdialogbuttonbox.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QLineEdit \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qlineedit.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qtextcursor.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qtextformat.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpen.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qtextoption.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QMessageBox \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qmessagebox.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QTableWidget \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qtablewidget.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qtableview.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qabstractitemview.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qabstractscrollarea.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qabstractitemmodel.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qitemselectionmodel.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qabstractitemdelegate.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qstyleoption.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qabstractspinbox.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qvalidator.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qregularexpression.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qslider.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qabstractslider.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qstyle.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qtabbar.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qrubberband.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QTableWidgetItem \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QPushButton \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qpushbutton.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qabstractbutton.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QWidget \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QTableView \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QTextEdit \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qtextedit.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qtextdocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QApplication \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qapplication.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qcoreapplication.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qglobal.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qconfig.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qfeatures.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qsystemdetection.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qprocessordetection.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qtypeinfo.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qtypetraits.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qsysinfo.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qlogging.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qflags.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qbasicatomic.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qgenericatomic.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_mips.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_x86.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qatomic_unix.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qglobalstatic.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qmutex.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qnumeric.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qstring.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qchar.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qbytearray.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qrefcount.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qnamespace.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qarraydata.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qstringbuilder.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qobject.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qobjectdefs.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qlist.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qalgorithms.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qiterator.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qbytearraylist.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qstringlist.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qregexp.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qstringmatcher.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qcoreevent.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qscopedpointer.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qmetatype.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qisenum.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qobject_impl.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qeventloop.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qwindowdefs.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qpoint.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qsize.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qcursor.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qwidget.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qmargins.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpaintdevice.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qrect.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpalette.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qcolor.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qrgb.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qbrush.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qpair.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qvector.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qmatrix.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpolygon.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qregion.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qdatastream.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qiodevice.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qline.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qtransform.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpainterpath.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qimage.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpixelformat.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpixmap.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qsharedpointer.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qshareddata.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qhash.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qfont.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qfontmetrics.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qfontinfo.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qkeysequence.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qevent.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qvariant.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qmap.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qdebug.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qtextstream.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qlocale.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qset.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qurl.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qurlquery.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qfile.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qfiledevice.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qvector2d.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qtouchdevice.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qguiapplication.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qinputmethod.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/QMouseEvent \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QString \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QStringList \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QDebug \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QIODevice \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QTextCodec \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qtextcodec.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QMutex \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QProgressBar \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qprogressbar.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qframe.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QFileDialog \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qfiledialog.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qdir.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qfileinfo.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qdialog.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QMainWindow \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qicon.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QDialog \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QDialogButtonBox \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qdialogbuttonbox.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QLineEdit \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qlineedit.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qtextcursor.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qtextformat.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qpen.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qtextoption.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QMessageBox \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qmessagebox.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QTableWidget \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qtablewidget.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qtableview.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qabstractitemview.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qabstractscrollarea.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qabstractitemmodel.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qitemselectionmodel.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qabstractitemdelegate.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qstyleoption.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qabstractspinbox.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qvalidator.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/qregularexpression.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qslider.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qabstractslider.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qstyle.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qtabbar.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qrubberband.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QTableWidgetItem \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QPushButton \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qpushbutton.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qabstractbutton.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QWidget \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QTableView \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QTextEdit \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qtextedit.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtGui/qtextdocument.h \
		ui_mainwindow.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtCore/QVariant \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QAction \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qaction.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qactiongroup.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QButtonGroup \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qbuttongroup.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QHeaderView \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qheaderview.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QLabel \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qlabel.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QMenu \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qmenu.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QMenuBar \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/qmenubar.h \
		/opt/Qt5.5.1/5.5/gcc/include/QtWidgets/QSlider
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

